cursos=["HTML","CSS","JS",["PYTHON","RUBY"]]

cores=["rosa","roxo","verde",cursos] // ARRAY DENTRO DE UMA ARRAY = MATRIZES


//console.log( cursos) //IMPRIME TODOOS ELEMENTOS DO ARRAY

cursos[2]="JAVASCRIPT"// ATRIBUINDO UM NOVO VALOR ELEMENTO DE INDICE 2 
// DENTRO DO ARRAY

cursos.push("c++") // ADICIONA  NO FINAL MAIS ELEMENTOS AO ARRAY
cursos.unshift("POO")// ADICIONA ELEMENTO AO ARRAY NO INICIO

cursos.pop() //DELETA O ELEMENTO QUE ESTIVER NO FINAL DO  ARRAY
cursos.shift() // DELETA O LELEMENTO QUE ESTIVER NO INICIO DO ARRAY



//console.log(cursos[2])
console.log(cores[3][3][1]) // IMPRIME O  ELEMENTO 3 DO ARRAY CORES "CURSOS" QUE VAI IMPRIMIR O  ARRAY DENTRO DO ARRAY CURSOS NA POSIÇÃO 1 QUE É RUBY..
